# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: database.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x06server\"\x07\n\x05\x45mpty\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cPingResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1a\n\tCarCreate\x12\r\n\x05owner\x18\x01 \x01(\t\"\x1c\n\nCarRequest\x12\x0e\n\x06\x63\x61r_id\x18\x01 \x01(\x05\"=\n\x08Location\x12\x0e\n\x06\x63\x61r_id\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61r_long\x18\x02 \x01(\x02\x12\x0f\n\x07\x63\x61r_lat\x18\x03 \x01(\x02\",\n\x0b\x43\x61rResponse\x12\x0e\n\x06\x63\x61r_id\x18\x01 \x01(\x05\x12\r\n\x05owner\x18\x02 \x01(\t\"1\n\x0c\x43\x61rsResponse\x12!\n\x04\x63\x61rs\x18\x01 \x03(\x0b\x32\x13.server.CarResponse\"g\n\x10LocationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06\x63\x61r_id\x18\x02 \x01(\x05\x12\x10\n\x08\x63\x61r_long\x18\x03 \x01(\x02\x12\x0f\n\x07\x63\x61r_lat\x18\x04 \x01(\x02\x12\x0f\n\x07\x64\x62_time\x18\x05 \x01(\x01\"@\n\x11LocationsResponse\x12+\n\tlocations\x18\x01 \x03(\x0b\x32\x18.server.LocationResponse2;\n\x06Server\x12\x31\n\x04Ping\x12\x13.server.PingRequest\x1a\x14.server.PingResponse2=\n\x08\x44\x61tabase\x12\x31\n\x04Ping\x12\x13.server.PingRequest\x1a\x14.server.PingResponse2\xa5\x01\n\x03\x43\x61r\x12-\n\x03\x41\x64\x64\x12\x11.server.CarCreate\x1a\x13.server.CarResponse\x12\x39\n\x0b\x41\x64\x64Location\x12\x10.server.Location\x1a\x18.server.LocationResponse\x12\x34\n\x06Update\x12\x10.server.Location\x1a\x18.server.LocationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_PINGREQUEST']._serialized_start=35
  _globals['_PINGREQUEST']._serialized_end=65
  _globals['_PINGRESPONSE']._serialized_start=67
  _globals['_PINGRESPONSE']._serialized_end=98
  _globals['_CARCREATE']._serialized_start=100
  _globals['_CARCREATE']._serialized_end=126
  _globals['_CARREQUEST']._serialized_start=128
  _globals['_CARREQUEST']._serialized_end=156
  _globals['_LOCATION']._serialized_start=158
  _globals['_LOCATION']._serialized_end=219
  _globals['_CARRESPONSE']._serialized_start=221
  _globals['_CARRESPONSE']._serialized_end=265
  _globals['_CARSRESPONSE']._serialized_start=267
  _globals['_CARSRESPONSE']._serialized_end=316
  _globals['_LOCATIONRESPONSE']._serialized_start=318
  _globals['_LOCATIONRESPONSE']._serialized_end=421
  _globals['_LOCATIONSRESPONSE']._serialized_start=423
  _globals['_LOCATIONSRESPONSE']._serialized_end=487
  _globals['_SERVER']._serialized_start=489
  _globals['_SERVER']._serialized_end=548
  _globals['_DATABASE']._serialized_start=550
  _globals['_DATABASE']._serialized_end=611
  _globals['_CAR']._serialized_start=614
  _globals['_CAR']._serialized_end=779
# @@protoc_insertion_point(module_scope)
