# FROM python:3.13-slim

# WORKDIR /app

# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# COPY server.py .

# EXPOSE 50051

# CMD ["uvicorn", "post_server:app", "--host", "0.0.0.0", "--port", "8001", "--no-access-log"]