FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY database_pb2.py .
COPY database_pb2_grpc.py .
COPY server/post_server.py .

EXPOSE 50051

CMD ["uvicorn", "post_server:app", "--host", "0.0.0.0", "--port", "8001", "--no-access-log"]